version: '3'

services:
  mysql:
    hostname: localhost
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: 1234
      MYSQL_USER: root
    networks:
      - code-network
  
  phpmyadmin:
    hostname: localhost
    # image: phpmyadmin/phpmyadmin:5-fpm-alpine
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:db
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - code-network

  web:
    hostname: localhost
    container_name: server
    image: nginx:1.13.12-alpine
    restart: always
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - fpm
    ports:
      - "80:80"
    networks:
      - code-network

  fpm:
    hostname: localhost
    container_name: php-fpm
    build: ./docker/php/
    restart: always
    volumes:
      - ./www/:/var/www/
    ports:
      - 9000:9000
    networks:
      - code-network
    depends_on:
      - mysql

networks:
  code-network:
    driver: bridge
